- name: Setup Wireguard server
  hosts: wg_server
  tasks:
    - name: Install wireguard
      apt:
        name:
          - wireguard
          - wireguard-tools
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: Generate Server wg-config
      template:
        src: wg_interface.j2
        dest: "/etc/wireguard/{{ wg_interface }}.conf"
      notify: read wg config
    - name: Gemerate debian-specific interface-config
      template:
        src: debian_interface.j2
        dest: "/etc/network/interfaces.d/{{ wg_interface }}"
      when: ansible_facts['os_family'] == "Debian"
      notify: reload interface
  handlers:
    - name: read wg config
      command: "wg setconf {{ wg_interface }} /etc/wireguard/{{ wg_interface }}.conf"
    - name: reload interface
      shell: "ifdown {{ wg_interface }}; ifup {{ wg_interface }}"
- name: Generate client configs
  hosts: localhost
  tasks:
    - name: Ensure cient conf directory exists
      file:
        path: wg_clients
        state: directory
    - name: generate client config
      template:
        src: wg_client.j2
        dest: "wg_clients/wg_{{ item }}.conf"
      with_items: "{{ groups['wg_clients'] | list }}"
