- name: Generate Wireguard server config
  hosts: wg_server
  tasks:
    - name: Generate Server wg-config
      template:
        src: wg_interface.j2
        dest: "/etc/wireguard/{{ wg_interface }}.conf"
      notify: read wg config
  handlers:
    - name: read wg config
      command: "wg setconf {{ wg_interface }} /etc/wireguard/{{ wg_interface }}.conf"
- name: Generate client configs
  hosts: localhost
  tasks:
    - name: Ensure cient conf directory exists
      file:
        path: wg_clients
        state: directory
    - name: generate client config
      template:
        src: wg_client.j2
        dest: wg_clients/wg_{{ item }}.conf
      with_items: "{{ groups['wg_clients'] | list }}"
